FROM quay.io/toolbx-images/alpine-toolbox:edge


RUN apk update && \
  apk upgrade && \
  apk add git

RUN ln -fs /bin/sh /usr/bin/sh && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update

RUN echo "Wow such alpine. Very edge. Much container. So test."