name: Test container workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  SUPPORT: latest
  AKMODS_FLAVOR: main
  MAJOR_VERSION: 39
  IMAGE_VARIANT: nokmods
  IMAGE_NAME: silverblue

jobs:
  run-main-build:
    name: Build uBlue-OS Main
    continue-on-error: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        uses: ./
        with:
          container_ref: main
          push_container: "false"
          file: ./test/Containerfile
          support: ${{ env.SUPPORT }}
          target: ${{ env.IMAGE_NAME }}
          image_name: ${{ env.IMAGE_NAME }}
          version: ${{ env.MAJOR_VERSION }}
          image_variant: ${{ env.IMAGE_VARIANT }}
          signing_key: ${{ secrets.SIGNING_SECRET }}
          container_registry: ghcr.io/${{ github.repository }}
          container_repo: bayou-brogrammer/cosmos-container-action
          extra_build_args: |
            AKMODS_FLAVOR=${{ env.AKMODS_FLAVOR }}
